export default {
  brandPrimaryPure: '#ED1C24',
  brandPrimaryLight: '#FBC6CB',
  brandPrimaryMedium: '#D51118',
  brandPrimaryDark: '#5E080B',

  brandSecondaryPure: '#BD8D28',
  brandSecondaryLight: '#EEDAAF',
  brandSecondaryMedium: '#976220',
  brandSecondaryDark: '#6E4017',

  accentPure: '#6339F9',
  accentLight: '#D4C3FE',
  accentMedium: '#3E27B0',
  accentDark: '#2B245D',

  neutralHighPure: '#FFFFFF',
  neutralHighLight: '#F5F5F4',
  neutralHighMedium: '#E4E3E1',
  neutralHighDark: '#B7B2AE',

  neutralLowPure: '#131211',
  neutralLowLight: '#958F88',
  neutralLowMedium: '#645E59',
  neutralLowDark: '#3B3835',

  statusFocusPure: '#009DF2',
  statusFocusLight: '#B3E6F4',
  statusFocusMedium: '#005BAE',
  statusFocusDark: '#143971',

  statusNegativePure: '#C51B62',
  statusNegativeLight: '#FAC7D2',
  statusNegativeMedium: '#9D0261',

  bgDefault: '$neutralLowPure',
  bgSoft: '$neutralLowDark',
  bgBrand: '$brandPrimaryPure',
  bgBrandHover: '$brandPrimaryMedium',
  bgInverse: '$neutralHighPure',
  bgInverseHover: '$neutralHighLight',
  bgContrast: '$brandSecondaryPure',
  bgContrastHover: '$brandSecondaryMedium',
  bgDisabled: '$neutralLowMedium',
  bgNegative: '$statusNegativePure',

  fgDefault: '$neutralLowPure',
  fgSoft: '$neutralLowLight',
  fgBrand: '$brandPrimaryPure',
  fgBrandHover: '$brandPrimaryMedium',
  fgOnBrand: '$neutralHighPure',
  fgInverse: '$neutralHighPure',
  fgInverseHover: '$neutralHighMedium',
  fgOnContrast: '$neutralLowPure',
  fgDisabled: '$neutralHighDark',
  fgNegative: '$statusNegativePure',
  fgFocus: '$statusFocusPure',
};
