export default {
  brandPrimaryPure: '#288154ff',
  brandPrimaryLight: '#5acd8bff',
  brandPrimaryMedium: '#226d35ff',
  brandPrimaryDark: '#205527ff',

  brandSecondaryPure: '#a7e833ff',
  brandSecondaryLight: '#d5f49fff',
  brandSecondaryMedium: '#2ba423ff',
  brandSecondaryDark: '#288154ff',

  accentPure: '#ff2a00',
  accentLight: '#ffbdad',
  accentMedium: '#e12b00',
  accentDark: '#751600',

  neutralHighPure: '#ffffffff',
  neutralHighLight: '#eef0ebff',
  neutralHighMedium: '#d2d7cbff',
  neutralHighDark: '#8d977d',

  neutralLowPure: '#272924ff',
  neutralLowLight: '#6d7561ff',
  neutralLowMedium: '#3f4338ff',
  neutralLowDark: '#1a1c17ff',

  statusFocusPure: '#7b86d1ff',
  statusFocusLight: '#ced2eeff',
  statusFocusMedium: '#414e9fff',
  statusFocusDark: '#293160ff',

  statusNegativePure: '#dd1d60ff',
  statusNegativeLight: '#f5b2caff',
  statusNegativeMedium: '#ac164bff',
  statusNegativeDark: '#680d2dff',

  bgDefault: '$neutralHighPure',
  bgSoft: '$neutralHighLight',
  bgBrand: '$brandPrimaryPure',
  bgBrandHover: '$brandPrimaryMedium',
  bgInverse: '$neutralLowPure',
  bgInverseHover: '$neutralLowMedium',
  bgContrast: '$neutralHighPure',
  bgContrastHover: '$neutralHighLight',
  bgDisabled: '$neutralHighMedium',
  bgNegative: '$statusNegativePure',

  fgDefault: '$neutralLowPure',
  fgSoft: '$neutralLowLight',
  fgBrand: '$brandPrimaryPure',
  fgBrandHover: '$brandPrimaryMedium',
  fgOnBrand: '$neutralHighPure',
  fgInverse: '$neutralHighPure',
  fgInverseHover: '$neutralHighMedium',
  fgOnContrast: '$neutralLowPure',
  fgDisabled: '$neutralHighDark',
  fgNegative: '$statusNegativePure',
  fgFocus: '$statusFocusPure',
};
