export default {
  brandPrimaryPure: '#003087',
  brandPrimaryLight: '#6198FF',
  brandPrimaryMedium: '#002466',
  brandPrimaryDark: '#001438',

  brandSecondaryPure: '#ED8B00',
  brandSecondaryLight: '#FFCC84',
  brandSecondaryMedium: '#BD6E00',
  brandSecondaryDark: '#4C2D00',

  accentPure: '#CA8C4E',
  accentLight: '#F2B982',
  accentMedium: '#AD7338',
  accentDark: '#613A13',

  neutralHighPure: '#FFFFFF',
  neutralHighLight: '#F8F9FA',
  neutralHighMedium: '#E1E5E9',
  neutralHighDark: '#BBBCBC',

  neutralLowPure: '#001438',
  neutralLowLight: '#848F9A',
  neutralLowMedium: '#49566E',
  neutralLowDark: '#1F2D47',

  statusFocusPure: '#00B8B8',
  statusFocusLight: '#00F5F5',
  statusFocusMedium: '#007A7A',
  statusFocusDark: '#003333',

  statusNegativePure: '#D12929',
  statusNegativeLight: '#F76E6E',
  statusNegativeMedium: '#B31818',
  statusNegativeDark: '#5A0C0C',

  bgDefault: '$neutralLowPure',
  bgSoft: '$neutralLowDark',
  bgBrand: '$brandPrimaryPure',
  bgBrandHover: '$brandPrimaryMedium',
  bgInverse: '$neutralHighPure',
  bgInverseHover: '$neutralHighLight',
  bgContrast: '$brandSecondaryPure',
  bgContrastHover: '$brandSecondaryMedium',
  bgDisabled: '$neutralLowMedium',
  bgNegative: '$statusNegativePure',

  fgDefault: '$neutralLowPure',
  fgSoft: '$neutralLowLight',
  fgBrand: '$brandPrimaryPure',
  fgBrandHover: '$brandPrimaryMedium',
  fgOnBrand: '$neutralHighPure',
  fgInverse: '$neutralHighPure',
  fgInverseHover: '$neutralHighMedium',
  fgOnContrast: '$neutralLowPure',
  fgDisabled: '$neutralHighDark',
  fgNegative: '$statusNegativePure',
  fgFocus: '$statusFocusPure',
};
